server:
  port: 8081
spring:
  application:
    name: Benchmarker Config Server
  cloud:
    config:
      profile: default
      label: master
      server:
        git:
          uri: https://github.com/socbrasns/bm-data-config-files.git
          username: fulviusguelfi
          password: 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
          clone-on-start: true
          skipSslValidation: true
          deleteUntrackedBranches: true
      enabled: true
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: https://bm-data-config.herokuapp.com/
          name: Benchmarker Config Server
          metadata:
            user: 
              name: shaddowuser
              password: H7T*$
        url:
        - http://bm-data-service-admin.herokuapp.com/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'